### ISSUE TITLE
Attempting to delete a blueprint causes a 500

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#156]

**Comment by ryanmark** [comment]
```
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`autotune_staging`.`autotune_blueprint_tags`, CONSTRAINT `fk_rails_7a10cacbf3` FOREIGN KEY (`blueprint_id`) REFERENCES `autotune_blueprints` (`id`))
  active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
    log(sql, name) { @connection.query(sql) }
  active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
    log(sql, name) { @connection.query(sql) }
  active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
    :binds          => binds) { yield }
  active_support/notifications/instrumenter.rb:20:in `instrument'
    yield payload
  active_record/connection_adapters/abstract_adapter.rb:460:in `log'
    @instrumenter.instrument(
...
(95 additional frame(s) were not displayed)

ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`autotune_staging`.`autotune_blueprint_tags`, CONSTRAINT `fk_rails_7a10cacbf3` FOREIGN KEY (`blueprint_id`) REFERENCES `autotune_blueprints` (`id`)): DELETE FROM `autotune_blueprints` WHERE `autotune_blueprints`.`id` = 4
  active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
    log(sql, name) { @connection.query(sql) }
  active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
    log(sql, name) { @connection.query(sql) }
  active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
    :binds          => binds) { yield }
  active_support/notifications/instrumenter.rb:20:in `instrument'
    yield payload
  active_record/connection_adapters/abstract_adapter.rb:460:in `log'
    @instrumenter.instrument(
...
(95 additional frame(s) were not displayed)
```

**Comment by ryanmark** [comment]
I think this is actually related to blueprint tags for some reason.

**Comment by ryanmark** [comment]
dupe of #147
